grafana:
  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
   limits:
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 128Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://umbrella-chart-kube-promet-prometheus.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: false
          # basicAuth: true
          # basicAuthUser: user #change it when needed
          # secureJsonData:
          #   basicAuthPassword: pass #change it when needed

  persistence:
    enabled: false  # Set to true with PVC config in production

  ingress:
    enabled: false  # You can set this to true later when exposing via Ingress