kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      serviceMonitorSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: true
      retention: 10d
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          memory: "1Gi"
  alertmanager:
    enabled: true
  grafana:
    enabled: false